sonar.sourceEncoding=UTF-8
sonar.sources=frontend/src,backend/src
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/*.spec.ts
