sonar.sourceEncoding=UTF-8
sonar.sources=frontend/src,backend/src
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=frontend/src/**,backend/src/database/entities/**,backend/src/database/migrations/**,backend/src/database/database.module.ts,backend/src/database/typeorm.options.ts,backend/src/database/data-source.ts
sonar.cpd.exclusions=backend/src/database/migrations/**
