export enum ApplicationStateReason {
  METRICS_MISSING = 'METRICS_MISSING',
  SOURCE_TIMEOUT = 'SOURCE_TIMEOUT',
  SOURCE_ERROR = 'SOURCE_ERROR',
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  INVALID_FIELD = 'INVALID_FIELD',
  MONITORING_CYCLE_DELAYED = 'MONITORING_CYCLE_DELAYED',
  CARBON_FACTOR_UNAVAILABLE = 'CARBON_FACTOR_UNAVAILABLE',
}
